<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BancosSeeder extends Seeder
{
    public function run()
    {
        $bancos = [
            ['clave' => '002', 'banco' => 'BANAMEX', 'descripcion' => 'Banco Nacional de México, S.A., Institución de Banca Múltiple, Grupo Financiero Banamex'],
            ['clave' => '006', 'banco' => 'BANCOMEXT', 'descripcion' => 'Banco Nacional de Comercio Exterior, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo'],
            ['clave' => '009', 'banco' => 'BANOBRAS', 'descripcion' => 'Banco Nacional de Obras y Servicios Públicos, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo'],
            ['clave' => '012', 'banco' => 'BBVA BANCOMER', 'descripcion' => 'BBVA Bancomer, S.A., Institución de Banca Múltiple, Grupo Financiero BBVA Bancomer'],
            ['clave' => '014', 'banco' => 'SANTANDER', 'descripcion' => 'Banco Santander (México), S.A., Institución de Banca Múltiple, Grupo Financiero Santander'],
            ['clave' => '019', 'banco' => 'BANJERCITO', 'descripcion' => 'Banco Nacional del Ejército, Fuerza Aérea y Armada, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo'],
            ['clave' => '021', 'banco' => 'HSBC', 'descripcion' => 'HSBC México, S.A., institución De Banca Múltiple, Grupo Financiero HSBC'],
            ['clave' => '030', 'banco' => 'BAJIO', 'descripcion' => 'Banco del Bajío, S.A., Institución de Banca Múltiple'],
            ['clave' => '032', 'banco' => 'IXE', 'descripcion' => 'IXE Banco, S.A., Institución de Banca Múltiple, IXE Grupo Financiero'],
            ['clave' => '036', 'banco' => 'INBURSA', 'descripcion' => 'Banco Inbursa, S.A., Institución de Banca Múltiple, Grupo Financiero Inbursa'],
            ['clave' => '037', 'banco' => 'INTERACCIONES', 'descripcion' => 'Banco Interacciones, S.A., Institución de Banca Múltiple'],
            ['clave' => '042', 'banco' => 'MIFEL', 'descripcion' => 'Banca Mifel, S.A., Institución de Banca Múltiple, Grupo Financiero Mifel'],
            ['clave' => '044', 'banco' => 'SCOTIABANK', 'descripcion' => 'Scotiabank Inverlat, S.A.'],
            ['clave' => '058', 'banco' => 'BANREGIO', 'descripcion' => 'Banco Regional de Monterrey, S.A., Institución de Banca Múltiple, Banregio Grupo Financiero'],
            ['clave' => '059', 'banco' => 'INVEX', 'descripcion' => 'Banco Invex, S.A., Institución de Banca Múltiple, Invex Grupo Financiero'],
            ['clave' => '060', 'banco' => 'BANSI', 'descripcion' => 'Bansi, S.A., Institución de Banca Múltiple'],
            ['clave' => '062', 'banco' => 'AFIRME', 'descripcion' => 'Banca Afirme, S.A., Institución de Banca Múltiple'],
            ['clave' => '072', 'banco' => 'BANORTE', 'descripcion' => 'Banco Mercantil del Norte, S.A., Institución de Banca Múltiple, Grupo Financiero Banorte'],
            ['clave' => '102', 'banco' => 'THE ROYAL BANK', 'descripcion' => 'The Royal Bank of Scotland México, S.A., Institución de Banca Múltiple'],
            ['clave' => '103', 'banco' => 'AMERICAN EXPRESS', 'descripcion' => 'American Express Bank (México), S.A., Institución de Banca Múltiple'],
            ['clave' => '106', 'banco' => 'BAMSA', 'descripcion' => 'Bank of America México, S.A., Institución de Banca Múltiple, Grupo Financiero Bank of America'],
            ['clave' => '108', 'banco' => 'TOKYO', 'descripcion' => 'Bank of Tokyo-Mitsubishi UFJ (México), S.A.'],
            ['clave' => '110', 'banco' => 'JP MORGAN', 'descripcion' => 'Banco J.P. Morgan, S.A., Institución de Banca Múltiple, J.P. Morgan Grupo Financiero'],
            ['clave' => '112', 'banco' => 'BMONEX', 'descripcion' => 'Banco Monex, S.A., Institución de Banca Múltiple'],
            ['clave' => '113', 'banco' => 'VE POR MAS', 'descripcion' => 'Banco Ve Por Mas, S.A. Institución de Banca Múltiple'],
            ['clave' => '116', 'banco' => 'ING', 'descripcion' => 'ING Bank (México), S.A., Institución de Banca Múltiple, ING Grupo Financiero'],
            ['clave' => '124', 'banco' => 'DEUTSCHE', 'descripcion' => 'Deutsche Bank México, S.A., Institución de Banca Múltiple'],
            ['clave' => '126', 'banco' => 'CREDIT SUISSE', 'descripcion' => 'Banco Credit Suisse (México), S.A. Institución de Banca Múltiple, Grupo Financiero Credit Suisse (México)'],
            ['clave' => '127', 'banco' => 'AZTECA', 'descripcion' => 'Banco Azteca, S.A. Institución de Banca Múltiple'],
            ['clave' => '128', 'banco' => 'AUTOFIN', 'descripcion' => 'Banco Autofin México, S.A. Institución de Banca Múltiple'],
            ['clave' => '129', 'banco' => 'BARCLAYS', 'descripcion' => 'Barclays Bank México, S.A., Institución de Banca Múltiple, Grupo Financiero Barclays México'],
            ['clave' => '130', 'banco' => 'COMPARTAMOS', 'descripcion' => 'Banco Compartamos, S.A., Institución de Banca Múltiple'],
            ['clave' => '131', 'banco' => 'BANCO FAMSA', 'descripcion' => 'Banco Ahorro Famsa, S.A., Institución de Banca Múltiple'],
            ['clave' => '132', 'banco' => 'BMULTIVA', 'descripcion' => 'Banco Multiva, S.A., Institución de Banca Múltiple, Multivalores Grupo Financiero'],
            ['clave' => '133', 'banco' => 'ACTINVER', 'descripcion' => 'Banco Actinver, S.A. Institución de Banca Múltiple, Grupo Financiero Actinver'],
            ['clave' => '134', 'banco' => 'WAL-MART', 'descripcion' => 'Banco Wal-Mart de México Adelante, S.A., Institución de Banca Múltiple'],
            ['clave' => '135', 'banco' => 'NAFIN', 'descripcion' => 'Nacional Financiera, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo'],
            ['clave' => '136', 'banco' => 'INTERBANCO', 'descripcion' => 'Inter Banco, S.A. Institución de Banca Múltiple'],
            ['clave' => '137', 'banco' => 'BANCOPPEL', 'descripcion' => 'BanCoppel, S.A., Institución de Banca Múltiple'],
            ['clave' => '138', 'banco' => 'ABC CAPITAL', 'descripcion' => 'ABC Capital, S.A., Institución de Banca Múltiple'],
            ['clave' => '139', 'banco' => 'UBS BANK', 'descripcion' => 'UBS Bank México, S.A., Institución de Banca Múltiple, UBS Grupo Financiero'],
            ['clave' => '140', 'banco' => 'CONSUBANCO', 'descripcion' => 'Consubanco, S.A. Institución de Banca Múltiple'],
            ['clave' => '141', 'banco' => 'VOLKSWAGEN', 'descripcion' => 'Volkswagen Bank, S.A., Institución de Banca Múltiple'],
            ['clave' => '143', 'banco' => 'CIBANCO', 'descripcion' => 'CIBanco, S.A.'],
            ['clave' => '145', 'banco' => 'BBASE', 'descripcion' => 'Banco Base, S.A., Institución de Banca Múltiple'],
            ['clave' => '166', 'banco' => 'BANSEFI', 'descripcion' => 'Banco del Ahorro Nacional y Servicios Financieros, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo'],
            ['clave' => '168', 'banco' => 'HIPOTECARIA FEDERAL', 'descripcion' => 'Sociedad Hipotecaria Federal, Sociedad Nacional de Crédito, Institución de Banca de Desarrollo'],
            ['clave' => '600', 'banco' => 'MONEXCB', 'descripcion' => 'Monex Casa de Bolsa, S.A. de C.V. Monex Grupo Financiero'],
            ['clave' => '601', 'banco' => 'GBM', 'descripcion' => 'GBM Grupo Bursátil Mexicano, S.A. de C.V. Casa de Bolsa'],
            ['clave' => '602', 'banco' => 'MASARI', 'descripcion' => 'Masari Casa de Bolsa, S.A.'],
            ['clave' => '605', 'banco' => 'VALUE', 'descripcion' => 'Value, S.A. de C.V. Casa de Bolsa'],
            ['clave' => '606', 'banco' => 'ESTRUCTURADORES', 'descripcion' => 'Estructuradores del Mercado de Valores Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '607', 'banco' => 'TIBER', 'descripcion' => 'Casa de Cambio Tiber, S.A. de C.V.'],
            ['clave' => '608', 'banco' => 'VECTOR', 'descripcion' => 'Vector Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '610', 'banco' => 'B&B', 'descripcion' => 'B y B, Casa de Cambio, S.A. de C.V.'],
            ['clave' => '614', 'banco' => 'ACCIVAL', 'descripcion' => 'Acciones y Valores Banamex, S.A. de C.V., Casa de Bolsa'],
            ['clave' => '615', 'banco' => 'MERRILL LYNCH', 'descripcion' => 'Merrill Lynch México, S.A. de C.V. Casa de Bolsa'],
            ['clave' => '616', 'banco' => 'FINAMEX', 'descripcion' => 'Casa de Bolsa Finamex, S.A. de C.V.'],
            ['clave' => '617', 'banco' => 'VALMEX', 'descripcion' => 'Valores Mexicanos Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '618', 'banco' => 'UNICA', 'descripcion' => 'Unica Casa de Cambio, S.A. de C.V.'],
            ['clave' => '619', 'banco' => 'MAPFRE', 'descripcion' => 'MAPFRE Tepeyac, S.A.'],
            ['clave' => '620', 'banco' => 'PROFUTURO', 'descripcion' => 'Profuturo G.N.P., S.A. de C.V., Afore'],
            ['clave' => '621', 'banco' => 'CB ACTINVER', 'descripcion' => 'Actinver Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '622', 'banco' => 'OACTIN', 'descripcion' => 'OPERADORA ACTINVER, S.A. DE C.V.'],
            ['clave' => '623', 'banco' => 'SKANDIA', 'descripcion' => 'Skandia Vida, S.A. de C.V.'],
            ['clave' => '626', 'banco' => 'CBDEUTSCHE', 'descripcion' => 'Deutsche Securities, S.A. de C.V. CASA DE BOLSA'],
            ['clave' => '627', 'banco' => 'ZURICH', 'descripcion' => 'Zurich Compañía de Seguros, S.A.'],
            ['clave' => '628', 'banco' => 'ZURICHVI', 'descripcion' => 'Zurich Vida, Compañía de Seguros, S.A.'],
            ['clave' => '629', 'banco' => 'SU CASITA', 'descripcion' => 'Hipotecaria Su Casita, S.A. de C.V. SOFOM ENR'],
            ['clave' => '630', 'banco' => 'CB INTERCAM', 'descripcion' => 'Intercam Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '631', 'banco' => 'CI BOLSA', 'descripcion' => 'CI Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '632', 'banco' => 'BULLTICK', 'descripcion' => 'CB Bulltick Casa de Bolsa, S.A., de C.V.'],
            ['clave' => '633', 'banco' => 'STERLING', 'descripcion' => 'Sterling Casa de Cambio, S.A. de C.V.'],
            ['clave' => '634', 'banco' => 'FINCOMUN', 'descripcion' => 'Fincomún, Servicios Financieros Comunitarios, S.A. de C.V.'],
            ['clave' => '636', 'banco' => 'HDI SEGUROS', 'descripcion' => 'HDI Seguros, S.A. de C.V.'],
            ['clave' => '637', 'banco' => 'ORDER', 'descripcion' => 'Order Express Casa de Cambio, S.A. de C.V'],
            ['clave' => '638', 'banco' => 'AKALA', 'descripcion' => 'Akala, S.A. de C.V., Sociedad Financiera Popular'],
            ['clave' => '640', 'banco' => 'CB JPMORGAN', 'descripcion' => 'J.P. Morgan Casa de Bolsa, S.A. de C.V. J.P. Morgan Grupo Financiero'],
            ['clave' => '642', 'banco' => 'REFORMA', 'descripcion' => 'Operadora de Recursos Reforma, S.A. de C.V., S.F.P.'],
            ['clave' => '643', 'banco' => 'STP', 'descripcion' => 'Sistema de Transferencias y Pagos STP, S.A. de C.V.SOFOM ENR'],
            ['clave' => '644', 'banco' => 'TELECOMM', 'descripcion' => 'Telecomunicaciones de México'],
            ['clave' => '645', 'banco' => 'EVERCORE', 'descripcion' => 'Evercore Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '646', 'banco' => 'SKANDIA', 'descripcion' => 'Skandia Operadora de Fondos, S.A. de C.V.'],
            ['clave' => '647', 'banco' => 'SEGMTY', 'descripcion' => 'Seguros Monterrey New York Life, S.A de C.V'],
            ['clave' => '648', 'banco' => 'ASEA', 'descripcion' => 'Solución Asea, S.A. de C.V., Sociedad Financiera Popular'],
            ['clave' => '649', 'banco' => 'KUSPIT', 'descripcion' => 'Kuspit Casa de Bolsa, S.A. de C.V.'],
            ['clave' => '650', 'banco' => 'SOFIEXPRESS', 'descripcion' => 'J.P. SOFIEXPRESS, S.A. de C.V., S.F.P.'],
            ['clave' => '651', 'banco' => 'UNAGRA', 'descripcion' => 'UNAGRA, S.A. de C.V., S.F.P.'],
            ['clave' => '652', 'banco' => 'OPCIONES EMPRESARIALES DEL NOROESTE', 'descripcion' => 'OPCIONES EMPRESARIALES DEL NORTE, S.A. DE C.V., S.F.P.'],
            ['clave' => '653', 'banco' => 'COMUN', 'descripcion' => 'Caja Popular Comun, S.A. de C.V.'],
            ['clave' => '654', 'banco' => 'CAJA TELEFONISTAS', 'descripcion' => 'Caja Popular de Ahorros de los Telefonistas'],
            ['clave' => '655', 'banco' => 'SOFIEXPRESS', 'descripcion' => 'J.P. SOFIEXPRESS, S.A. de C.V., S.F.P.'],
            ['clave' => '656', 'banco' => 'UNAGRA', 'descripcion' => 'UNAGRA, S.A. de C.V., S.F.P.'],
            ['clave' => '659', 'banco' => 'OPCIONES EMPRESARIALES DEL NOROESTE', 'descripcion' => 'OPCIONES EMPRESARIALES DEL NORTE, S.A. DE C.V., S.F.P.'],
            ['clave' => '901', 'banco' => 'CLS', 'descripcion' => 'Cls Bank International'],
            ['clave' => '902', 'banco' => 'INDEVAL SD.', 'descripcion' => 'Indeval, S.A. de C.V.'],
            ['clave' => '670', 'banco' => 'LIBERTAD', 'descripcion' => 'Libertad Servicios Financieros, S.A. De C.V.'],
            ['clave' => '999', 'banco' => 'N/A', 'descripcion' => 'No disponible'],
        ];

        foreach ($bancos as $banco) {
            DB::table('bancos')->insert($banco);
        }
    }
}
